version: '3.7'


# container to run tests and other developer activities
services:
  php:
    container_name: pyrus_client_symfony
    image: pyrus_client_symfony
    build:
      context: php
    volumes:
      - ./../:/var/app:cached
