services:

  SuareSu\PyrusClientSymfony\FormConverter\PyrusFormConverterFinalizer:
    class: SuareSu\PyrusClientSymfony\FormConverter\PyrusFormConverterFinalizerImpl
    arguments:
      - '@translator'

  SuareSu\PyrusClientSymfony\FormConverter\PyrusFormConverter:
    class: SuareSu\PyrusClientSymfony\FormConverter\PyrusFormConverterImpl
    arguments:
      - '@form.factory'
      - !tagged_iterator pyrus_client_symfony.field_converter
      - '@SuareSu\PyrusClientSymfony\FormConverter\PyrusFormConverterFinalizer'
      - '%suare_su_pyrus_client_symfony.ignore_unknown_types%'

  SuareSu\PyrusClientSymfony\FormConverter\FieldConverter\PyrusFieldConverterCheckMark:
    class: SuareSu\PyrusClientSymfony\FormConverter\FieldConverter\PyrusFieldConverterCheckMark
    tags: 
      - { name: 'pyrus_client_symfony.field_converter', priority: -2000 }

  SuareSu\PyrusClientSymfony\FormConverter\FieldConverter\PyrusFieldConverterDate:
    class: SuareSu\PyrusClientSymfony\FormConverter\FieldConverter\PyrusFieldConverterDate
    tags: 
      - { name: 'pyrus_client_symfony.field_converter', priority: -2000 }

  SuareSu\PyrusClientSymfony\FormConverter\FieldConverter\PyrusFieldConverterDueDateTime:
    class: SuareSu\PyrusClientSymfony\FormConverter\FieldConverter\PyrusFieldConverterDueDateTime
    tags: 
      - { name: 'pyrus_client_symfony.field_converter', priority: -2000 }

  SuareSu\PyrusClientSymfony\FormConverter\FieldConverter\PyrusFieldConverterEmail:
    class: SuareSu\PyrusClientSymfony\FormConverter\FieldConverter\PyrusFieldConverterEmail
    tags: 
      - { name: 'pyrus_client_symfony.field_converter', priority: -2000 }

  SuareSu\PyrusClientSymfony\FormConverter\FieldConverter\PyrusFieldConverterFile:
    class: SuareSu\PyrusClientSymfony\FormConverter\FieldConverter\PyrusFieldConverterFile
    tags: 
      - { name: 'pyrus_client_symfony.field_converter', priority: -2000 }

  SuareSu\PyrusClientSymfony\FormConverter\FieldConverter\PyrusFieldConverterIgnore:
    class: SuareSu\PyrusClientSymfony\FormConverter\FieldConverter\PyrusFieldConverterIgnore
    tags: 
      - { name: 'pyrus_client_symfony.field_converter', priority: -2000 }

  SuareSu\PyrusClientSymfony\FormConverter\FieldConverter\PyrusFieldConverterMoney:
    class: SuareSu\PyrusClientSymfony\FormConverter\FieldConverter\PyrusFieldConverterMoney
    tags: 
      - { name: 'pyrus_client_symfony.field_converter', priority: -2000 }

  SuareSu\PyrusClientSymfony\FormConverter\FieldConverter\PyrusFieldConverterNumber:
    class: SuareSu\PyrusClientSymfony\FormConverter\FieldConverter\PyrusFieldConverterNumber
    tags: 
      - { name: 'pyrus_client_symfony.field_converter', priority: -2000 }

  SuareSu\PyrusClientSymfony\FormConverter\FieldConverter\PyrusFieldConverterPhone:
    class: SuareSu\PyrusClientSymfony\FormConverter\FieldConverter\PyrusFieldConverterPhone
    tags: 
      - { name: 'pyrus_client_symfony.field_converter', priority: -2000 }

  SuareSu\PyrusClientSymfony\FormConverter\FieldConverter\PyrusFieldConverterText:
    class: SuareSu\PyrusClientSymfony\FormConverter\FieldConverter\PyrusFieldConverterText
    tags: 
      - { name: 'pyrus_client_symfony.field_converter', priority: -2000 }

  SuareSu\PyrusClientSymfony\FormConverter\FieldConverter\PyrusFieldConverterTextMultipleChoice:
    class: SuareSu\PyrusClientSymfony\FormConverter\FieldConverter\PyrusFieldConverterTextMultipleChoice
    tags: 
      - { name: 'pyrus_client_symfony.field_converter', priority: -2000 }

  SuareSu\PyrusClientSymfony\FormConverter\FieldConverter\PyrusFieldConverterTime:
    class: SuareSu\PyrusClientSymfony\FormConverter\FieldConverter\PyrusFieldConverterTime
    tags: 
      - { name: 'pyrus_client_symfony.field_converter', priority: -2000 }


  SuareSu\PyrusClientSymfony\FormValueExtractor\PyrusFormValueExtractor:
    class: SuareSu\PyrusClientSymfony\FormValueExtractor\PyrusFormValueExtractorImpl
    arguments:
      - !tagged_iterator pyrus_client_symfony.field_extractor

  SuareSu\PyrusClientSymfony\FormValueExtractor\FieldValueBuilder\PyrusFormFieldValueBuilderMultipleChoice:
    class: SuareSu\PyrusClientSymfony\FormValueExtractor\FieldValueBuilder\PyrusFormFieldValueBuilderMultipleChoice
    tags: 
      - { name: 'pyrus_client_symfony.field_extractor', priority: -2000 }

  SuareSu\PyrusClientSymfony\FormValueExtractor\FieldValueBuilder\PyrusFormFieldValueBuilderFile:
    class: SuareSu\PyrusClientSymfony\FormValueExtractor\FieldValueBuilder\PyrusFormFieldValueBuilderFile
    arguments:
      - '%suare_su_pyrus_client_symfony.path_to_save_uploaded_files%'
    tags: 
      - { name: 'pyrus_client_symfony.field_extractor', priority: -2000 }

  SuareSu\PyrusClientSymfony\FormValueExtractor\FieldValueBuilder\PyrusFormFieldValueBuilderDefault:
    class: SuareSu\PyrusClientSymfony\FormValueExtractor\FieldValueBuilder\PyrusFormFieldValueBuilderDefault
    tags: 
      - { name: 'pyrus_client_symfony.field_extractor', priority: -3000 }