services:

  SuareSu\PyrusClient\Transport\PyrusTransport:
    class: SuareSu\PyrusClientSymfony\PyrusSymfonyHttpTransport
    arguments:
      - '@http_client'

  SuareSu\PyrusClient\Client\PyrusClientOptions:
    class: SuareSu\PyrusClient\Client\PyrusClientOptions

  SuareSu\PyrusClientSymfony\PyrusSerializer:
    tags: 
      - { name: 'serializer.normalizer', priority: -200 }
      - { name: 'serializer.denormalizer', priority: -200 }

  SuareSu\PyrusClient\DataConverter\PyrusDataConverter:
    class: SuareSu\PyrusClientSymfony\PyrusDataConverterSymfonySerializer
    arguments:
      - '@serializer'
      - '@serializer'

  Marvin255\InMemoryCache\InMemoryCache:
    class: Marvin255\InMemoryCache\InMemoryCache
    public: false
    arguments:
      - 10
      - 60
      - '@clock'

  SuareSu\PyrusClientSymfony\PyrusGatewayFactoryImpl:
    class: SuareSu\PyrusClientSymfony\PyrusGatewayFactoryImpl
    public: false
    arguments:
      - '@SuareSu\PyrusClient\Transport\PyrusTransport'
      - '@SuareSu\PyrusClient\DataConverter\PyrusDataConverter'
      - '@SuareSu\PyrusClient\Client\PyrusClientOptions'

  SuareSu\PyrusClientSymfony\PyrusGatewayFactoryCache:
    class: SuareSu\PyrusClientSymfony\PyrusGatewayFactoryCache
    public: false
    arguments:
      - '@SuareSu\PyrusClientSymfony\PyrusGatewayFactoryImpl'
      - '@Marvin255\InMemoryCache\InMemoryCache'

  SuareSu\PyrusClientSymfony\PyrusGatewayFactory:
    alias: 'SuareSu\PyrusClientSymfony\PyrusGatewayFactoryCache'